<?php
    $this->partial("head");
?>
<nav class="nav has-shadow">
    <div class="container">
        <div class="nav-left">
            <a class="nav-item is-tab" href="#status">
                Status Query
            </a>
            <a class="nav-item is-tab" href="#players">
                Players Query
            </a>
            <a class="nav-item is-tab" href="#info">
                Info Query
            </a>
        </div>
    </div>
</nav>
<section class="section">
    <div class="container">
        <div class="columns is-multiline">
            <div class="column is-12">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Required</th>
                                        <th>Parameter</th>
                                        <th>Type</th>
                                        <th>Description</th>
                                        <th>Default Value</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th>True</th>
                                        <th>IP</th>
                                        <td>String</td>
                                        <td>Server's IP address or domain</td>
                                        <td>None</td>
                                    </tr>
                                    <tr>
                                        <th>False</th>
                                        <th>Port</th>
                                        <td>Integer</td>
                                        <td>The port of which the game server is running on.</td>
                                        <td>27015</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-12">
                <h1 class="title" id="status"><a href="#status">Status Query</a></h1>
            </div>
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Single Server</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div class="request-url"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/cs/query/status/{IP}:{PORT}</div>
                            <pre><code class="hljs json">{
    "status": true,
    "hostname": "{IP}",
    "port": {PORT},
    "queryPort": {PORT},
    "protocol": "udp",
    "cached": false
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Multiple Servers</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div class="request-url"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/cs/query/status/{IP}:{PORT},{IP2}:{PORT2}</div>
                            <pre><code class="hljs json">{
    "{IP}:{PORT}": {
        "status": true,
        "hostname": "{IP}",
        "port": {PORT},
        "queryPort": {PORT},
        "protocol": "udp",
        "cached": false
    },
    "{IP2}:{PORT2}": {
        "status": true,
        "hostname": "{IP2}",
        "port": {PORT2},
        "queryPort": {PORT2},
        "protocol": "udp",
        "cached": false
    }
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns is-multiline">
            <div class="column is-12">
                <h1 class="title" id="players"><a href="#players">Players Query</a></h1>
            </div>
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Single Server</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div class="request-url"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/cs/query/players/{IP}:{PORT}</div>
                            <pre><code class="hljs json">{
    "status": true,
    "hostname": "{IP}",
    "port": {PORT},
    "queryPort": {PORT},
    "protocol": "udp",
    "players": {
        "online": 2,
        "max": 32,
        "list": [
            {
                "name": "Player",
                "score": 0,
                "time": {
                    "seconds": 622.31860351562,
                    "minutes": 10.37197672526,
                    "hours": 0.17286627875434
                }
            },
            {
                "name": "TAZ",
                "score": 9,
                "time": {
                    "seconds": 348.03500366211,
                    "minutes": 5.8005833943685,
                    "hours": 0.096676389906141
                }
            }
        ]
    },
    "cached": false
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Multiple Servers</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div class="request-url"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/cs/query/players/{IP}:{PORT},{IP2}:{PORT2}</div>
                            <pre><code class="hljs json">{
    "{IP}:{PORT}": {
        "status": true,
        "hostname": "{IP}",
        "port": {PORT},
        "queryPort": {PORT},
        "protocol": "udp",
        "players": {
            "online": 2,
            "max": 32,
            "list": [
                {
                    "name": "Player",
                    "score": 0,
                    "time": {
                        "seconds": 622.31860351562,
                        "minutes": 10.37197672526,
                        "hours": 0.17286627875434
                    }
                },
                {
                    "name": "TAZ",
                    "score": 9,
                    "time": {
                        "seconds": 348.03500366211,
                        "minutes": 5.8005833943685,
                        "hours": 0.096676389906141
                    }
                }
            ]
        },
        "cached": false
    },
    "{IP2}:{PORT2}": {
        "status": true,
        "hostname": "{IP2}",
        "port": {PORT2},
        "queryPort": {PORT2},
        "protocol": "udp",
        "players": {
            "online": 0,
            "max": 32,
            "list": null
        },
        "cached": false
    }
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns is-multiline">
            <div class="column is-12">
                <h1 class="title" id="info"><a href="#info">Info Query</a></h1>
            </div>
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Single Server</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div class="request-url"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/cs/query/info/{IP}:{PORT}</div>
                            <pre><code class="hljs json">{
    "status": true,
    "hostname": "{IP}",
    "port": {PORT},
    "queryPort": {PORT},
    "protocol": "udp",
    "name": "cs 1.6 server",
    "map": "de_dust2",
    "vac_secured": true,
    "password_protected": false,
    "join": "steam://connect/{IP}:{PORT}/",
    "version": "1.1.2.7/Stdio",
    "protocol": 48,
    "players": {
        "online": 2,
        "max": 32,
        "list": [
            {
                "name": "Player",
                "score": 0,
                "time": {
                    "seconds": 622.31860351562,
                    "minutes": 10.37197672526,
                    "hours": 0.17286627875434
                }
            },
            {
                "name": "TAZ",
                "score": 9,
                "time": {
                    "seconds": 348.03500366211,
                    "minutes": 5.8005833943685,
                    "hours": 0.096676389906141
                }
            }
        ]
    },
    "cached": false
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Multiple Servers</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div class="request-url"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/cs/query/info/{IP}:{PORT},{IP2}:{PORT2}</div>
                            <pre><code class="hljs json">{
    "{IP}:{PORT}": {
        "status": true,
        "hostname": "{IP}",
        "port": {PORT},
        "queryPort": {PORT},
        "name": "cs 1.6 server",
        "map": "de_dust2",
        "vac_secured": true,
        "password_protected": false,
        "join": "steam://connect/{IP}:{PORT}/",
        "version": "1.1.2.7/Stdio",
        "protocol": "udp",
        "players": {
            "online": 2,
            "max": 32,
            "list": [
                {
                    "name": "Player",
                    "score": 0,
                    "time": {
                        "seconds": 622.31860351562,
                        "minutes": 10.37197672526,
                        "hours": 0.17286627875434
                    }
                },
                {
                    "name": "TAZ",
                    "score": 9,
                    "time": {
                        "seconds": 348.03500366211,
                        "minutes": 5.8005833943685,
                        "hours": 0.096676389906141
                    }
                }
            ]
        },
        "cached": false
    },
    "{IP2}:{PORT2}": {
        "status": true,
        "hostname": "{IP}",
        "port": {PORT2},
        "queryPort": {PORT2},
        "name": "cs 1.6 server",
        "map": "de_inferno",
        "vac_secured": true,
        "password_protected": false,
        "join": "steam://connect/{IP2}:{PORT2}/",
        "version": "1.1.2.7/Stdio",
        "protocol": "udp",
        "players": {
            "online": 0,
            "max": 32,
            "list": null
        },
        "cached": false
    }
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php
    $this->partial("footer");
?>
