<?php
    $this->partial("head");
?>
<script>hljs.initHighlightingOnLoad();</script>
<nav class="nav has-shadow">
    <div class="container">
        <div class="nav-left">
            <a class="nav-item is-tab is-active" href="#">
                Status
            </a>
            <a class="nav-item is-tab" href="/supported/minecraft/query/info">
                Info
            </a>
            <a class="nav-item is-tab" href="/supported/minecraft/query/motd">
                MOTD
            </a>
            <a class="nav-item is-tab" href="/supported/minecraft/query/players">
                Players
            </a>
            <a class="nav-item is-tab" href="/supported/minecraft/query/icon">
                Icon
            </a>
            <a class="nav-item is-tab" href="/supported/minecraft/query/extensive">
                Extensive
            </a>
        </div>
    </div>
</nav>
<section class="section">
    <div class="container">
        <div class="tile is-ancestor">
            <div class="tile is-vertical is-12">
                <div class="tile is-parent">
                    <article class="tile is-child">
                        <p class="title is-2">Status API</p>
                        <p class="subtitle is-4">Determine if a Minecraft server is offline or not</p>
                    </article>
                </div>
            </div>
        </div>
        <hr>
        <div class="tile is-ancestor">
            <div class="tile is-vertical">
                <div class="tile">
                    <div class="tile is-parent">
                        <article class="tile is-child">
                            <p class="title">Successful Response</p>
                            <div class="content">
                                <pre><code class="json">{
    "status": true,
    "hostname": "play.minesuperior.com",
    "port": 25565,
    "ping": 46,
    "cached": false
}</code></pre>
                            </div>
                        </article>
                    </div>
                </div>
            </div>
            <div class="tile is-parent">
                <article class="tile is-child">
                    <p class="title">Failed Response</p>
                    <div class="content">
                        <pre><code class="json">{
    "status": false,
    "hostname": "play.minesuperior.com",
    "port": 25565,
    "error": "Failed to connect or create a socket: 110 (Connection timed out)",
    "cached": false
}</code></pre>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>
<!--
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column">
                <h3 class="title is-2 is-spaced">Status</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column is-one-third">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Usage</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <hr>
                <h3 class="title is-2 is-spaced">Info</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column is-one-third">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Usage</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <hr>
                <h3 class="title is-2 is-spaced">Multi Info</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column is-one-third">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Usage</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <hr>
                <h3 class="title is-2 is-spaced">MOTD</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column is-one-third">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Usage</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <hr>
                <h3 class="title is-2 is-spaced">Players</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column is-one-third">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Usage</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <hr>
                <h3 class="title is-2 is-spaced">Icon</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column is-one-third">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Usage</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <hr>
                <h3 class="title is-2 is-spaced">Extensive</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column is-one-third">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Usage</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <hr>
                <h3 class="title is-2 is-spaced">Multi Extensive</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column is-one-third">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Usage</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
-->
<?php
    $this->partial("footer");
?>
