<?php
    $this->partial("head");
?>
<nav class="nav has-shadow">
    <div class="container">
        <div class="nav-left">
            <a class="nav-item is-tab is-active" href="#">
                Home
            </a>
            <a class="nav-item is-tab" href="#">
                Guidelines
            </a>
            <a class="nav-item is-tab" href="#">
                Changelog
            </a>
            <a class="nav-item is-tab" href="#">
                Issue Tracker
            </a>
        </div>
    </div>
</nav>
<section class="section">
    <div class="container">
        <div class="notification is-danger">This API service is a work in progress. Currently this is the public alpha version of the project.</div>
    </div>
</section>
<?php /*
<section class="section">
    <div class="container">
        <div class="columns is-multiline">
            <div class="column is-12">
                <h2 class="title is-2">Features</h2>
                <hr>
            </div>
            <div class="column is-one-quarter-mobile is-one-third-tablet is-one-third-desktop">
                <div class="card">
                    <div class="card-image">
                        <figure class="image">
                            <img src="/img/games.jpg" alt="Mumble">
                        </figure>
                    </div>
                </div>
            </div>
            <div class="column is-three-quarters-mobile is-two-thirds-tablet is-two-thirds-desktop">
                <h2 class="title">Large Library of Supported Games</h2>
                <p>something goes here, but I'm not creative enough</p>
            </div>
            <div class="column is-12">
                <hr>
            </div>
            <div class="column is-three-quarters-mobile is-two-thirds-tablet is-two-thirds-desktop">
                <h2 class="title">something goes here, but I'm not creative enough</h2>
                <p>something goes here, but I'm not creative enough</p>
            </div>
            <div class="column is-one-quarter-mobile is-one-third-tablet is-one-third-desktop">
                <div class="card">
                    <div class="card-image">
                        <figure class="image">
                            <img src="/img/games.jpg" alt="Mumble">
                        </figure>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
*/
    $this->partial("footer");
?>
