<?php
    $this->partial("head");
?>
<nav class="nav has-shadow">
    <div class="container">
        <div class="nav-left">
            <a class="nav-item is-tab is-active" href="#">
                Home
            </a>
            <a class="nav-item is-tab" href="/overview/guidelines">
                Guidelines
            </a>
            <a class="nav-item is-tab" href="/overview/contact">
                Contact
            </a>
        </div>
    </div>
</nav>
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column">
                <h3 class="title is-2 is-spaced">Features</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column is-one-third">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Usage</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php
    $this->partial("footer");
?>
