<?php
    $this->partial("head");

    $games = array(
        '7d2d' => array(
            'name' => '7 Days To Die',
            'link' => '/docs/7d2d',
            'file' => '/img/games/7d2d.jpg'
        ),
        'alienswarm' => array(
            'name' => 'Alien Swarm',
            'link' => '/docs/alienswarm',
            'file' => '/img/games/alienswarm.jpg'
        ),
        'ark' => array(
            'name' => 'Ark: Survival Evolved',
            'link' => '/docs/ark',
            'file' => '/img/games/ark.jpg'
        ),
        'arma2' => array(
            'name' => 'Arma 2',
            'link' => '/docs/arma2',
            'file' => '/img/games/arma2.jpg'
        ),
        'arma3' => array(
            'name' => 'Arma 3',
            'link' => '/docs/arma3',
            'file' => '/img/games/arma3.jpg'
        ),
        'bf2' => array(
            'name' => 'Battlefield 2',
            'link' => '/docs/bf2',
            'file' => '/img/games/bf2.jpg'
        ),
        'bf3' => array(
            'name' => 'Battlefield 3',
            'link' => '/docs/bf3',
            'file' => '/img/games/bf3.jpg'
        ),
        'bf4' => array(
            'name' => 'Battlefield 4',
            'link' => '/docs/bf4',
            'file' => '/img/games/bf4.jpg'
        ),
        'bf1942' => array(
            'name' => 'Battlefield 1942',
            'link' => '/docs/bf1942',
            'file' => '/img/games/bf1942.jpg'
        ),
        'bfbc2' => array(
            'name' => 'Battlefield: Bad Company 2',
            'link' => '/docs/bfbc2',
            'file' => '/img/games/bfbc2.jpg'
        ),
        'bfhl' => array(
            'name' => 'Battlefield: Hardline',
            'link' => '/docs/bfhl',
            'file' => '/img/games/bfhl.jpg'
        ),
        'ce' => array(
            'name' => 'Conan Exiles',
            'link' => '/docs/ce',
            'file' => '/img/games/ce.jpg'
        ),
        'cmw' => array(
            'name' => 'Chivalry: Medieval Warfare',
            'link' => '/docs/cmw',
            'file' => '/img/games/cmw.jpg'
        ),
        'cod2' => array(
            'name' => 'Call of Duty 2',
            'link' => '/docs/cod2',
            'file' => '/img/games/cod2.jpg'
        ),
        'cod4' => array(
            'name' => 'Call of Duty 4',
            'link' => '/docs/cod4',
            'file' => '/img/games/cod4.jpg'
        ),
        'codmw3' => array(
            'name' => 'Call of Duty: Modern Warfare 3',
            'link' => '/docs/codmw3',
            'file' => '/img/games/codmw3.jpg'
        ),
        'codwaw' => array(
            'name' => 'Call of Duty: World at War',
            'link' => '/docs/codwaw',
            'file' => '/img/games/codwaw.jpg'
        ),
        'cs' => array(
            'name' => 'Counter Strike 1.6',
            'link' => '/docs/cs',
            'file' => '/img/games/cs.jpg'
        ),
        'csco' => array(
            'name' => 'Counter Strike: Classic Offensive',
            'link' => '/docs/csco',
            'file' => '/img/games/csco.png'
        ),
        'csgo' => array(
            'name' => 'Counter Strike: Global Offensive',
            'link' => '/docs/csgo',
            'file' => '/img/games/csgo.jpg'
        ),
        'css' => array(
            'name' => 'Counter Strike Source',
            'link' => '/docs/css',
            'file' => '/img/games/css.jpg'
        ),
        'dayz' => array(
            'name' => 'DayZ',
            'link' => '/docs/dayz',
            'file' => '/img/games/dayz.jpg'
        ),
        'dods' => array(
            'name' => 'Day of Defeat: Source',
            'link' => '/docs/dods',
            'file' => '/img/games/dods.jpg'
        ),
        'gmod' => array(
            'name' => 'Garry\'s Mod',
            'link' => '/docs/gmod',
            'file' => '/img/games/gmod.jpg'
        ),
        'gta5' => array(
            'name' => 'Grand Theft Auto 5',
            'link' => '/docs/gta5',
            'file' => '/img/games/gta5.jpg'
        ),
        'gtasa' => array(
            'name' => 'Grand Theft Auto: San Andreas',
            'link' => '/docs/gtasa',
            'file' => '/img/games/gtasa.jpg'
        ),
        'hl2dm' => array(
            'name' => 'Half Life 2: Deathmatch',
            'link' => '/docs/hl2dm',
            'file' => '/img/games/hl2dm.jpg'
        ),
        'hw' => array(
            'name' => 'Hurtworld',
            'link' => '/docs/hw',
            'file' => '/img/games/hw.jpg'
        ),
        'insurgency' => array(
            'name' => 'Insurgency',
            'link' => '/docs/insurgency',
            'file' => '/img/games/insurgency.jpg'
        ),
        'kf' => array(
            'name' => 'Killing Floor',
            'link' => '/docs/kf',
            'file' => '/img/games/kf.jpg'
        ),
        'kf2' => array(
            'name' => 'Killing Floor 2',
            'link' => '/docs/kf2',
            'file' => '/img/games/kf2.jpg'
        ),
        'l4d' => array(
            'name' => 'Left 4 Dead',
            'link' => '/docs/l4d',
            'file' => '/img/games/l4d.jpg'
        ),
        'l4d2' => array(
            'name' => 'Left 4 Dead 2',
            'link' => '/docs/l4d2',
            'file' => '/img/games/l4d2.jpg'
        ),
        'mc' => array(
            'name' => 'Minecraft',
            'link' => '/docs/mc',
            'file' => '/img/games/mc.jpg'
        ),
        'mcpe' => array(
            'name' => 'Minecraft Pocket Edition',
            'link' => '/docs/mcpe',
            'file' => '/img/games/mcpe.jpg'
        ),
        'mohaa' => array(
            'name' => 'Medal of Honor: Allied Assault',
            'link' => '/docs/mohaa',
            'file' => '/img/games/mohaa.jpg'
        ),
        'ns2' => array(
            'name' => 'Natural Selection 2',
            'link' => '/docs/ns2',
            'file' => '/img/games/ns2.jpg'
        ),
        'ql' => array(
            'name' => 'Quake Live',
            'link' => '/docs/ql',
            'file' => '/img/games/ql.jpg'
        ),
        'ro2' => array(
            'name' => 'Red Orchestra 2',
            'link' => '/docs/ro2',
            'file' => '/img/games/ro2.jpg'
        ),
        'rust' => array(
            'name' => 'Rust',
            'link' => '/docs/rust',
            'file' => '/img/games/rust.jpg'
        ),
        'se' => array(
            'name' => 'Space Engineers',
            'link' => '/docs/se',
            'file' => '/img/games/se.jpg'
        ),
        'squad' => array(
            'name' => 'SQUAD',
            'link' => '/docs/squad',
            'file' => '/img/games/squad.jpg'
        ),
        'sb' => array(
            'name' => 'Starbound',
            'link' => '/docs/sb',
            'file' => '/img/games/sb.jpg'
        ),
        'terraria' => array(
            'name' => 'Terraria',
            'link' => '/docs/terraria',
            'file' => '/img/games/terraria.jpg'
        ),
        'tf2' => array(
            'name' => 'Team Fortress 2',
            'link' => '/docs/tf2',
            'file' => '/img/games/tf2.jpg'
        ),
        'unturned' => array(
            'name' => 'Unturned',
            'link' => '/docs/unturned',
            'file' => '/img/games/unturned.jpg'
        ),
        'wu' => array(
            'name' => 'Wurm Unlimited',
            'link' => '/docs/wu',
            'file' => '/img/games/wu.jpg'
        )
    );
?>
<nav class="nav has-shadow">
    <div class="container">
        <div class="nav-left">
            <a class="nav-item is-tab is-active" href="#">
                Game Servers
            </a>
        </div>
    </div>
</nav>
<section class="section">
    <div class="container">
        <div class="notification is-danger">This API service is a work in progress. You can view the temporary <a href="https://gist.github.com/Yive/579ad48324c3bb0eae7ccfb3dba3b912">Github Gist</a> to see what games are planned to be supported.</div>
        <div class="columns is-multiline">
            <?php
                $liveAPIs = array('7d2d','alienswarm','cs','csgo','css','gmod','mc','mcpe');
                foreach ($games as $key => $value) {
                    if(in_array($key, $liveAPIs)) {
                        echo '<div class="column is-half-mobile is-one-third-tablet is-one-quarter-desktop">
                            <div class="card shadow-hover">
                                <div class="card-image">
                                    <figure class="image">
                                        <img src="'.$value['file'].'" alt="'.$value['name'].'">
                                    </figure>
                                </div>
                                <a class="card-content button is-info is-fullwidth" style="border-radius:0;border:0px;" href="'.$value['link'].'">View Documentation</a>
                            </div>
                        </div>';
                    }
                }
             ?>
        </div>
    </div>
</section>
<?php
    $this->partial("footer");
?>
