<?php
    $this->partial("head");
?>
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column">
                <h3 class="title is-2 is-spaced">Features</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column is-one-third">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Usage</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="container">
    <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="thumbnail">
            <div class="caption">
                <center>
                    <h3>Minecraft PC</h3>
                    <p><a href="#" class="btn btn-primary" role="button">Discover APIs</a></p>
                </center>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="thumbnail">
            <div class="caption">
                <center>
                    <h3>Minecraft PE</h3>
                    <p><a href="#" class="btn btn-primary" role="button">Discover APIs</a></p>
                </center>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="thumbnail">
            <div class="caption">
                <center>
                    <h3>Factorio</h3>
                    <p><a href="#" class="btn btn-primary" role="button">Discover APIs</a></p>
                </center>
            </div>
        </div>
    </div>
</div>
<?php
    $this->partial("footer");
?>
