<?php
    $this->partial("head");

    $games = array(
        'mumble' => array(
            'name' => 'Mumble',
            'link' => '/docs/mumble',
            'file' => '/img/voice/mumble.jpg'
        ),
        'ts3' => array(
            'name' => 'TeamSpeak 3',
            'link' => '/docs/ts3',
            'file' => '/img/voice/ts3.jpg'
        )
    );
?>
<nav class="nav has-shadow">
    <div class="container">
        <div class="nav-left">
            <a class="nav-item is-tab" href="/">
                Game Servers
            </a>
            <a class="nav-item is-tab is-active" href="#">
                Voice Servers
            </a>
            <a class="nav-item is-tab" href="/protocol">
                Protocols
            </a>
        </div>
    </div>
</nav>
<section class="section">
    <div class="container">
        <div class="notification is-danger">This API service is a work in progress. Currently this is the public alpha version of the project.</div>
        <div class="columns is-multiline">
            <?php
                $liveAPIs = array('mumble','ts3');
                foreach ($games as $key => $value) {
                    if(in_array($key, $liveAPIs)) {
                        header("Link: <".$value['file'].">; rel=preload; as=image", false);
                        echo '<div class="column is-full-mobile is-one-third-tablet is-one-quarter-desktop">
                            <div class="card shadow-hover">
                                <div class="card-image">
                                    <figure class="image">
                                        <a href="'.$value['link'].'"><img src="'.$value['file'].'" alt="'.$value['name'].'"></a>
                                    </figure>
                                </div>
                                <a class="card-content button is-dark is-fullwidth" style="border-radius:0;border:0px;" href="'.$value['link'].'">View Documentation</a>
                            </div>
                        </div>';
                    }
                }
             ?>
        </div>
    </div>
</section>
<?php
    $this->partial("footer");
?>
