<script>
    $(window).scroll(function() {
        if ($(this).scrollTop() >= 300) {
            $('.goto-top').fadeIn(200);
        } else {
            $('.goto-top').fadeOut(200);
        }
    });
    $('.goto-top').click(function() {
        $('body,html').animate({
            scrollTop : 0
        }, 500);
    });
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-52657458-7', 'auto');
    ga('send', 'pageview');
</script>