<html>
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta property="og:title" content="GameAPIs"/>
        <meta property="og:type" content="website"/>
        <meta property="og:description" content="API service for game servers."/>
        <?php echo $this->tag->getTitle(); ?>
        <link href="/css/bulma.min.css" rel="stylesheet"/>
        <link href="/css/font-awesome.min.css" rel="stylesheet"/>
        <link href="/css/vs2015.min.css" rel="stylesheet"/>
        <link href="/css/main.css" rel="stylesheet"/>
        <script src="/js/jquery.min.js"></script>
        <script src="/js/highlight.min.js"></script>
        <script>
            hljs.initHighlightingOnLoad();
        </script>
    </head>
    <body>
        <a href="javascript:" class="goto-top"><i class="fa fa-chevron-up" aria-hidden="true"></i></a>
        <?php
            switch (true) {
                case strpos($this->tag->getTitle(), "Documentation") !== false: {
                    switch (true) {
                        case strpos($this->tag->getTitle(), " Documentation") !== false: {
                            $subtitle = str_replace("<title>","",str_replace(" - GameAPIs</title>","",$this->tag->getTitle()));
                            $button = str_replace("<title>","",str_replace(" - GameAPIs</title>","",str_replace(" Documentation","",$this->tag->getTitle())));
                            break;
                        }
                        default: {
                            $subtitle = "Documentation";
                            break;
                        }
                    }
                    break;
                }
                case strpos($this->tag->getTitle(), "404") !== false: {
                    $subtitle = 404;
                    break;
                }
                default: {
                    $subtitle = "API Web Service For Game Servers";
                    break;
                }
            }
         ?>
        <section class="hero is-dark">
            <div class="hero-head">
                <header class="nav">
                    <div class="container">
                        <div class="nav-left">
                            <a class="nav-item" href="/">Home</a>
                        </div>
                        <div class="nav-right nav-menu">
                            <a class="nav-item" href="https://twitter.com/ItsYive">Twitter</a>
                            <a class="nav-item" href="https://github.com/GameAPIs/Issues/issues">Issue Tracker</a>
                        </div>
                    </div>
                </header>
            </div>
            <div class="hero-body">
                <div class="container has-text-centered">
                    <h1 class="title">GameAPIs</h1>
                    <h2 class="subtitle"><?php echo $subtitle; ?></h2>
                </div>
            </div>

            <div class="hero-foot">
                <nav class="tabs is-boxed">
                    <div class="container">
                        <ul>
                            <li<?php if($subtitle == "Documentation") { echo " class=\"is-active\""; } ?>><a href="https://docs.gameapis.net">Documentation</a></li>
                            <?php if(!empty($button)) { echo '<li class="is-active"><a href="#">'.$button.'</a></li>'; } ?>
                        </ul>
                    </div>
                </nav>
            </div>
        </section>
