<?php
    $this->partial("includes/head");
?>
<div class="container">
    <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="thumbnail">
            <div class="caption">
                <center>
                    <h3>Minecraft PC</h3>
                    <p><a href="#" class="btn btn-primary" role="button">Discover APIs</a></p>
                </center>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="thumbnail">
            <div class="caption">
                <center>
                    <h3>Minecraft PE</h3>
                    <p><a href="#" class="btn btn-primary" role="button">Discover APIs</a></p>
                </center>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="thumbnail">
            <div class="caption">
                <center>
                    <h3>Factorio</h3>
                    <p><a href="#" class="btn btn-primary" role="button">Discover APIs</a></p>
                </center>
            </div>
        </div>
    </div>
</div>
<?php
    //$this->partial("includes/footer");
?>