<?php
    $this->partial("head");
?>
<nav class="nav has-shadow">
    <div class="container">
        <div class="nav-left">
            <a class="nav-item is-tab" href="/">
                Home
            </a>
            <a class="nav-item is-tab" href="/ui/mc/extra/blockedservers">
                BlockedServers Search
            </a>
        </div>
    </div>
</nav>
<section class="section">
    <div class="container">
        <div class="columns is-mobile is-multiline">
            <?php echo $this->getContent(); ?>
        </div>
    </div>
</section>
<?php
    $this->partial("footer");
?>