<?php
    $this->partial("includes/head");
?>
<style type="text/css">h3{margin-top: 10.5px;margin-bottom: 10.5px;}</style>
<div class="container">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <a class="thumbnail" href="/supported/minecraft/server-query">
            <div class="caption">
                <center>
                    <h3>Server Query</h3>
                </center>
            </div>
        </a>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <a class="thumbnail" href="/supported/minecraft/player-images">
            <div class="caption">
                <center>
                    <h3>Player Images</h3>
                </center>
            </div>
        </a>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <a class="thumbnail" href="/supported/minecraft/server-ecommerce">
            <div class="caption">
                <center>
                    <h3>Server Ecommerce</h3>
                </center>
            </div>
        </a>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <a class="thumbnail" href="/supported/minecraft/extra-apis">
            <div class="caption">
                <center>
                    <h3>Extra Minecraft APIs</h3>
                </center>
            </div>
        </a>
    </div>
</div>
<?php
    //$this->partial("includes/footer");
?>