<?php
    $this->partial("../includes/head");
?>
<nav class="nav has-shadow">
    <div class="container">
        <div class="nav-left">
            <a class="nav-item is-tab is-active">
                Home
            </a>
            <a class="nav-item is-tab" href="/supported/minecraft/query/status">
                Status
            </a>
            <a class="nav-item is-tab" href="/supported/minecraft/query/info">
                Info
            </a>
            <a class="nav-item is-tab" href="/supported/minecraft/query/motd">
                MOTD
            </a>
            <a class="nav-item is-tab" href="/supported/minecraft/query/players">
                Players
            </a>
            <a class="nav-item is-tab" href="/supported/minecraft/query/icon">
                Icon
            </a>
            <a class="nav-item is-tab" href="/supported/minecraft/query/extensive">
                Extensive
            </a>
        </div>
    </div>
</nav>
<section class="section">

</section>
<!--
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column">
                <h3 class="title is-2 is-spaced">Status</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column is-one-third">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Usage</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <hr>
                <h3 class="title is-2 is-spaced">Info</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column is-one-third">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Usage</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <hr>
                <h3 class="title is-2 is-spaced">Multi Info</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column is-one-third">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Usage</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <hr>
                <h3 class="title is-2 is-spaced">MOTD</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column is-one-third">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Usage</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <hr>
                <h3 class="title is-2 is-spaced">Players</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column is-one-third">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Usage</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <hr>
                <h3 class="title is-2 is-spaced">Icon</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column is-one-third">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Usage</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <hr>
                <h3 class="title is-2 is-spaced">Extensive</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column is-one-third">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Usage</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <hr>
                <h3 class="title is-2 is-spaced">Multi Extensive</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column is-one-third">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Usage</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p>Placeholder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
-->
<?php
    $this->partial("../includes/footer");
?>
