<?php
    $this->partial("head");
?>
<nav class="nav has-shadow">
    <div class="container">
        <div class="nav-left">
            <a class="nav-item is-tab" href="/docs/mc/query">Query</a>
            <a class="nav-item is-tab" href="/docs/mc/ecommerce">Ecommerce</a>
            <a class="nav-item is-tab" href="/docs/mc/images">Images</a>
            <a class="nav-item is-tab is-active" href="#">Extra</a>
        </div>
    </div>
</nav>
<section class="section" style="padding-top:1.5rem;">
    <div class="container">
        <div class="columns is-multiline">
            <div class="column is-12">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Required</th>
                                        <th>Parameter</th>
                                        <th>Type</th>
                                        <th>Description</th>
                                        <th>Default Value</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th>True</th>
                                        <th>IP</th>
                                        <td>String</td>
                                        <td>Domain or IP of a minecraft server.</td>
                                        <td>None</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-4">
                <h1 class="title" id="bls">BlockedServers List</h1>
            </div>
            <div class="column is-12">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Listing</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div style="background-color:#f5f5f5;border-bottom:1px solid rgba(10,10,10,.1);padding:.5rem;"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/mc/blockedservers</div>
                            <pre><code class="hljs json">{
    "blocked": [
        "27ae74becc8cd701b19f25d347faa71084f69acd",
        "709a849e4e7a986c8165083dccb9857bcb04c67b",
        "073ca448ef3d311218d7bd32d6307243ce22e7d0",
        "33839f4006d6044a3a6675c593fada6a690bb64d"
    ],
    "found": {
        "27ae74becc8cd701b19f25d347faa71084f69acd": {
            "sha1": "27ae74becc8cd701b19f25d347faa71084f69acd",
            "ip": "*.arkhamnetwork.org"
        },
        "073ca448ef3d311218d7bd32d6307243ce22e7d0": {
            "sha1": "073ca448ef3d311218d7bd32d6307243ce22e7d0",
            "ip": "*.diacraft.org"
        },
        "33839f4006d6044a3a6675c593fada6a690bb64d": {
            "sha1": "33839f4006d6044a3a6675c593fada6a690bb64d",
            "ip": "*.diacraft.de"
        }
    },
    "unknown": {
        "709a849e4e7a986c8165083dccb9857bcb04c67b": {
            "sha1": "709a849e4e7a986c8165083dccb9857bcb04c67b"
        }
    }
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-12">
                <h1 class="title" id="blc">BlockedServers Check</h1>
            </div>
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Single Check</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div style="background-color:#f5f5f5;border-bottom:1px solid rgba(10,10,10,.1);padding:.5rem;"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/mc/blockedservers/check/{IP}</div>
                            <pre><code class="hljs json">{
    "ecocitycraft.com": [
        {
            "domain": "*.blockgamemoney.trade",
            "sha1": "8f9c4eaa376b1c33bc71a8be8409c2e77bce0e7d",
            "blocked": false
        },
        {
            "domain": "*.mc.blockgamemoney.trade",
            "sha1": "e9fa6cacca896cb831e9db1a659b0495ba69efec",
            "blocked": false
        },
        {
            "domain": "mc.blockgamemoney.trade",
            "sha1": "77479af32d8257739267f80a311ef04b28119d2f",
            "blocked": false
        },
        {
            "domain": "*.ecocitycraft.com",
            "sha1": "18bb441d5e66d5d40b09d4e675105c14b08647d6",
            "blocked": false
        },
        {
            "domain": "ecocitycraft.com",
            "sha1": "c52e9bb013c4ef6e1c65390eba677421d3dfc0d5",
            "blocked": false
        }
    ]
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Multiple Checks</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div style="background-color:#f5f5f5;border-bottom:1px solid rgba(10,10,10,.1);padding:.5rem;"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/mc/blockedservers/check/{IP},{IP2}</div>
                            <pre><code class="hljs json">{
    "ecocitycraft.com": [
        {
            "domain": "*.blockgamemoney.trade",
            "sha1": "8f9c4eaa376b1c33bc71a8be8409c2e77bce0e7d",
            "blocked": false
        },
        {
            "domain": "*.mc.blockgamemoney.trade",
            "sha1": "e9fa6cacca896cb831e9db1a659b0495ba69efec",
            "blocked": false
        },
        {
            "domain": "mc.blockgamemoney.trade",
            "sha1": "77479af32d8257739267f80a311ef04b28119d2f",
            "blocked": false
        },
        {
            "domain": "*.ecocitycraft.com",
            "sha1": "18bb441d5e66d5d40b09d4e675105c14b08647d6",
            "blocked": false
        },
        {
            "domain": "ecocitycraft.com",
            "sha1": "c52e9bb013c4ef6e1c65390eba677421d3dfc0d5",
            "blocked": false
        }
    ],
    "arkhamnetwork.org": [
        {
            "domain": "*.youcantstopme.press",
            "sha1": "87dca2d59bbb223c2be3e2660d122079b040939a",
            "blocked": false
        },
        {
            "domain": "youcantstopme.press",
            "sha1": "3d87c540f012316881f9e9eb41a0367022d4d65c",
            "blocked": false
        },
        {
            "domain": "*.arkhamnetwork.org",
            "sha1": "27ae74becc8cd701b19f25d347faa71084f69acd",
            "blocked": true
        }
    ]
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-12">
                <h1 class="title" id="mcstatus">Minecraft Status</h1>
            </div>
            <div class="column is-12">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Status</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div style="background-color:#f5f5f5;border-bottom:1px solid rgba(10,10,10,.1);padding:.5rem;"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/mc/extra/status</div>
                            <pre><code class="hljs json">{
    "minecraft.net": {
        "status": "Online"
    },
    "session.minecraft.net": {
        "status": "Online"
    },
    "account.mojang.com": {
        "status": "Online"
    },
    "auth.mojang.com": {
        "status": "Online"
    },
    "skins.minecraft.net": {
        "status": "Online"
    },
    "authserver.mojang.com": {
        "status": "Online"
    },
    "sessionserver.mojang.com": {
        "status": "Online"
    },
    "api.mojang.com": {
        "status": "Online"
    },
    "textures.minecraft.net": {
        "status": "Online"
    },
    "mojang.com": {
        "status": "Online"
    }
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php
    $this->partial("footer");
?>
