<?php
    $this->partial("head");
?>
<nav class="nav has-shadow">
    <div class="container">
        <div class="nav-left">
            <a class="nav-item is-tab is-active" href="/docs/">
                Game Servers
            </a>
            <a class="nav-item is-tab" href="#">
                Voice Servers
            </a>
            <a class="nav-item is-tab" href="#">
                Other
            </a>
        </div>
    </div>
</nav>
<section class="section">
    <div class="container">
        <div class="columns is-multiline">
            <div class="column is-half-mobile is-one-third-tablet is-one-quarter-desktop">
                <div class="card shadow-hover">
                    <header class="card-header">
                        <p class="card-header-title">Server Query</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            View information about a Minecraft Server
                        </div>
                    </div>
                    <a class="card-content button is-dark is-fullwidth" style="border-radius:0;border:0px;" href="/docs/ts3" disabled>View Documentation</a>
                </div>
            </div>
            <div class="column is-half-mobile is-one-third-tablet is-one-quarter-desktop">
                <div class="card shadow-hover">
                    <header class="card-header">
                        <p class="card-header-title">Player Images</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            APIs utilizing player skins
                        </div>
                    </div>
                    <a class="card-content button is-dark is-fullwidth" style="border-radius:0;border:0px;" href="/docs/ts3" disabled>View Documentation</a>
                </div>
            </div>
            <div class="column is-half-mobile is-one-third-tablet is-one-quarter-desktop">
                <div class="card shadow-hover">
                    <header class="card-header">
                        <p class="card-header-title">Server Ecommerce</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            View information about a Minecraft Server's shop.
                        </div>
                    </div>
                    <a class="card-content button is-dark is-fullwidth" style="border-radius:0;border:0px;" href="/docs/ts3" disabled>View Documentation</a>
                </div>
            </div>
            <div class="column is-half-mobile is-one-third-tablet is-one-quarter-desktop">
                <div class="card shadow-hover">
                    <header class="card-header">
                        <p class="card-header-title">Extra</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            Extra Minecraft related APIs
                        </div>
                    </div>
                    <a class="card-content button is-dark is-fullwidth" style="border-radius:0;border:0px;" href="/docs/ts3" disabled>View Documentation</a>
                </div>
            </div>
        </div>
    </div>
</section>
<?php
    $this->partial("footer");
?>
