<?php
    $this->partial("head");
?>
<nav class="nav has-shadow">
    <div class="container">
        <div class="nav-left">
            <a class="nav-item is-tab is-active" href="#">Query</a>
            <a class="nav-item is-tab" href="/docs/mc/player">Player</a>
            <a class="nav-item is-tab" href="/docs/mc/ecommerce">Ecommerce</a>
            <a class="nav-item is-tab" href="/docs/mc/images">Images</a>
            <a class="nav-item is-tab" href="/docs/mc/extra">Extra</a>
        </div>
    </div>
</nav>
<section class="section" style="padding-top:1.5rem;">
    <div class="container">
        <div class="columns is-multiline">
            <div class="column is-12">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Parameters</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Required</th>
                                        <th>Parameter</th>
                                        <th>Type</th>
                                        <th>Description</th>
                                        <th>Default Value</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th>True</th>
                                        <th>IP</th>
                                        <td>String</td>
                                        <td>Server's IP address or domain</td>
                                        <td>None</td>
                                    </tr>
                                    <tr>
                                        <th>False</th>
                                        <th>Port</th>
                                        <td>Integer</td>
                                        <td>The port of which the Minecraft server is running on.</td>
                                        <td>25565</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-12">
                <h1 class="title" id="status"><a href="#status" style="text-decoration:none;color:black;">Status Query</a></h1>
            </div>
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Single Server</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div style="background-color:#f5f5f5;border-bottom:1px solid rgba(10,10,10,.1);padding:.5rem;"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/mc/query/status/{IP}:{PORT}</div>
                            <pre><code class="hljs json">{
    "status": true,
    "hostname": "{IP}",
    "port": {PORT},
    "ping": 2,
    "cached": false
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Multiple Servers</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div style="background-color:#f5f5f5;border-bottom:1px solid rgba(10,10,10,.1);padding:.5rem;"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/mc/query/status/{IP}:{PORT},{IP2}:{PORT2}</div>
                            <pre><code class="hljs json">{
    "{IP}:{PORT}": {
        "status": true,
        "hostname": "{IP}",
        "port": {PORT},
        "ping": 2,
        "cached": false
    },
    "{IP2}:{PORT2}": {
        "status": true,
        "hostname": "{IP2}",
        "port": {PORT2},
        "ping": 43,
        "cached": false
    }
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns is-multiline">
            <div class="column is-12">
                <hr>
                <h1 class="title" id="players"><a href="#players" style="text-decoration:none;color:black;">Players Query</a></h1>
            </div>
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Single Server</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div style="background-color:#f5f5f5;border-bottom:1px solid rgba(10,10,10,.1);padding:.5rem;"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/mc/query/players/{IP}:{PORT}</div>
                            <pre><code class="hljs json">{
    "status": true,
    "hostname": "{IP}",
    "port": {PORT},
    "players": {
        "online": 253,
        "max": 500
    },
    "cached": false
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Multiple Servers</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div style="background-color:#f5f5f5;border-bottom:1px solid rgba(10,10,10,.1);padding:.5rem;"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/mc/query/players/{IP}:{PORT},{IP2}:{PORT2}</div>
                            <pre><code class="hljs json">{
    "{IP}:{PORT}": {
        "status": true,
        "hostname": "{IP}",
        "port": {PORT},
        "players": {
            "online": 126,
            "max": 250
        },
        "cached": false
    },
    "{IP2}:{PORT2}": {
        "status": true,
        "hostname": "{IP2}",
        "port": {PORT2},
        "players": {
            "online": 382,
            "max": 500
        },
        "cached": false
    }
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns is-multiline">
            <div class="column is-12">
                <hr>
                <h1 class="title" id="info"><a href="#info" style="text-decoration:none;color:black;">Info Query</a></h1>
            </div>
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Single Server</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div style="background-color:#f5f5f5;border-bottom:1px solid rgba(10,10,10,.1);padding:.5rem;"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/mc/query/info/{IP}:{PORT}</div>
                            <pre><code class="hljs json">{
    "status": true,
    "hostname": "{IP}",
    "port": {PORT},
    "ping": 53,
    "version": "BungeeCord 1.8.x, 1.9.x, 1.10.x, 1.11.x",
    "protocol": 316,
    "players": {
        "online": 257,
        "max": 500
    },
    "motds": {
        "ingame": "§bMinecraft Server",
        "html": "&lt;span style=\"color:#55ffff\">Minecraft Server&lt;/span>",
        "clean": "Minecraft Server"
    },
    "favicon": "data:image/png;base64,{insert long base64 code}",
    "cached": false
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Multiple Servers</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div style="background-color:#f5f5f5;border-bottom:1px solid rgba(10,10,10,.1);padding:.5rem;"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/mc/query/info/{IP}:{PORT},{IP2}:{PORT2}</div>
                            <pre><code class="hljs json">{
    "{IP}:{PORT}": {
        "status": true,
        "hostname": "{IP}",
        "port": {PORT},
        "ping": 2,
        "version": "BungeeCord 1.8.x, 1.9.x, 1.10.x, 1.11.x",
        "protocol": 316,
        "players": {
            "online": 252,
            "max": 500
        },
        "motds": {
            "ingame": "§bMinecraft Server",
            "html": "&lt;span style=\"color:#55ffff\">Minecraft Server&lt;/span>",
            "clean": "Minecraft Server"
        },
        "favicon": "data:image/png;base64,{insert long base64 code}",
        "cached": false
    },
    "{IP2}:{PORT2}": {
        "status": true,
        "hostname": "{IP2}",
        "port": {PORT2},
        "ping": 3,
        "version": "BungeeCord 1.8.x-1.12.x",
        "protocol": 335,
        "players": {
            "online": 40,
            "max": 41
        },
        "motds": {
            "ingame": "§bMinecraft Server",
            "html": "&lt;span style=\"color:#55ffff\">Minecraft Server&lt;/span>",
            "clean": "Minecraft Server"
        },
        "favicon": "data:image/png;base64,{insert long base64 code}",
        "cached": false
    }
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns is-multiline">
            <div class="column is-12">
                <hr>
                <h1 class="title" id="icon"><a href="#icon" style="text-decoration:none;color:black;">Icon Query</a></h1>
            </div>
            <div class="column is-12">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Single Server</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div style="background-color:#f5f5f5;border-bottom:1px solid rgba(10,10,10,.1);padding:.5rem;"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/mc/query/icon/{IP}:{PORT}</div>
                            <pre><code class="hljs json"><img src="https://use.gameapis.net/mc/query/icon/mc.hypixel.net"/></code></pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns is-multiline">
            <div class="column is-12">
                <hr>
                <h1 class="title" id="motd"><a href="#motd" style="text-decoration:none;color:black;">MOTD Query</a></h1>
            </div>
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Single Server</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div style="background-color:#f5f5f5;border-bottom:1px solid rgba(10,10,10,.1);padding:.5rem;"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/mc/query/motd/{IP}:{PORT}</div>
                            <pre><code class="hljs json">{
    "status": true,
    "hostname": "{IP}",
    "port": {PORT},
    "ping": 53,
    "motds": {
        "ingame": "§bMinecraft Server",
        "html": "&lt;span style=\"color:#55ffff\">Minecraft Server&lt;/span>",
        "clean": "Minecraft Server"
    },
    "cached": false
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Multiple Servers</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div style="background-color:#f5f5f5;border-bottom:1px solid rgba(10,10,10,.1);padding:.5rem;"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/mc/query/motd/{IP}:{PORT},{IP2}:{PORT2}</div>
                            <pre><code class="hljs json">{
    "{IP}:{PORT}": {
        "status": true,
        "hostname": "{IP}",
        "port": {PORT},
        "ping": 2,
        "motds": {
            "ingame": "§bMinecraft Server",
            "html": "&lt;span style=\"color:#55ffff\">Minecraft Server&lt;/span>",
            "clean": "Minecraft Server"
        },
        "cached": false
    },
    "{IP2}:{PORT2}": {
        "status": true,
        "hostname": "{IP2}",
        "port": {PORT2},
        "ping": 3,
        "motds": {
            "ingame": "§bMinecraft Server",
            "html": "&lt;span style=\"color:#55ffff\">Minecraft Server&lt;/span>",
            "clean": "Minecraft Server"
        },
        "cached": false
    }
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns is-multiline">
            <div class="column is-12">
                <hr>
                <h1 class="title" id="extensive"><a href="#extensive" style="text-decoration:none;color:black;">Extensive Query</a> <span class="tag is-danger is-medium"><strong>enable-query</strong>&nbsp;needs to be set to true in server.properties.</span></h1>
            </div>
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Single Server</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div style="background-color:#f5f5f5;border-bottom:1px solid rgba(10,10,10,.1);padding:.5rem;"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/mc/query/extensive/{IP}:{PORT}</div>
                            <pre><code class="hljs json">{
    "status": true,
    "hostname": "{IP}",
    "port": {PORT},
    "version": "1.12",
    "software": "CraftBukkit on Bukkit 1.12-R0.1-SNAPSHOT",
    "game_type": "SMP",
    "game_name": "MINECRAFT",
    "motds": {
        "ingame": "§bMinecraft Server",
        "html": "&lt;span style=\"color:#55ffff\">Minecraft Server&lt;/span>",
        "clean": "Minecraft Server"
    },
    "map": "world",
    "players": {
        "online": 1,
        "max": 20
    },
    "list": [
        "Yive"
    ],
    "plugins": [
        "Vault 1.5.6-b49"
    ],
    "cached": false
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Multiple Servers</p>
                    </header>
                    <div class="card-content" style="padding:0;">
                        <div class="content">
                            <div style="background-color:#f5f5f5;border-bottom:1px solid rgba(10,10,10,.1);padding:.5rem;"><span class="tag is-dark" style="border-radius:0;">GET</span> https://use.gameapis.net/mc/query/extensive/{IP}:{PORT},{IP2}:{PORT2}</div>
                            <pre><code class="hljs json">{
    "{IP}:{PORT}": {
        "status": true,
        "hostname": "{IP}",
        "port": {PORT},
        "version": "1.12",
        "software": "CraftBukkit on Bukkit 1.12-R0.1-SNAPSHOT",
        "game_type": "SMP",
        "game_name": "MINECRAFT",
        "motds": {
            "ingame": "§bMinecraft Server",
            "html": "&lt;span style=\"color:#55ffff\">Minecraft Server&lt;/span>",
            "clean": "Minecraft Server"
        },
        "map": "world",
        "players": {
            "online": 1,
            "max": 20
        },
        "list": [
            "Yive"
        ],
        "plugins": [
            "Vault 1.5.6-b49"
        ],
        "cached": false
    },
    "{IP2}:{PORT2}": {
        "status": true,
        "hostname": "{IP2}",
        "port": {PORT2},
        "version": "1.12",
        "software": "CraftBukkit on Bukkit 1.12-R0.1-SNAPSHOT",
        "game_type": "SMP",
        "game_name": "MINECRAFT",
        "motds": {
            "ingame": "§bMinecraft Server",
            "html": "&lt;span style=\"color:#55ffff\">Minecraft Server&lt;/span>",
            "clean": "Minecraft Server"
        },
        "map": "world",
        "players": {
            "online": 0,
            "max": 20
        },
        "list": null,
        "plugins": [
            "Vault 1.5.6-b49"
        ],
        "cached": false
    }
}</code></pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php
    $this->partial("footer");
?>
